name: Node.js

on:
  push:
  pull_request:

jobs:
  test:
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
